//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 10:38:42 AM GMT 
//


package com.integ.integration.services.contracts.common.test.dto;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.integ.integration.services.contracts.common.test.dto package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.integ.integration.services.contracts.common.test.dto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DateDummyRequest }
     * 
     */
    public DateDummyRequest createDateDummyRequest() {
        return new DateDummyRequest();
    }

    /**
     * Create an instance of {@link DateDummyResponse }
     * 
     */
    public DateDummyResponse createDateDummyResponse() {
        return new DateDummyResponse();
    }

    /**
     * Create an instance of {@link NumericDummyRequest }
     * 
     */
    public NumericDummyRequest createNumericDummyRequest() {
        return new NumericDummyRequest();
    }

    /**
     * Create an instance of {@link NumericDummyResponse }
     * 
     */
    public NumericDummyResponse createNumericDummyResponse() {
        return new NumericDummyResponse();
    }

    /**
     * Create an instance of {@link ListsDummyRequest }
     * 
     */
    public ListsDummyRequest createListsDummyRequest() {
        return new ListsDummyRequest();
    }

    /**
     * Create an instance of {@link ListsDummyResponse }
     * 
     */
    public ListsDummyResponse createListsDummyResponse() {
        return new ListsDummyResponse();
    }

    /**
     * Create an instance of {@link AbstractDummyRequest }
     * 
     */
    public AbstractDummyRequest createAbstractDummyRequest() {
        return new AbstractDummyRequest();
    }

    /**
     * Create an instance of {@link AbstractDummyResponse }
     * 
     */
    public AbstractDummyResponse createAbstractDummyResponse() {
        return new AbstractDummyResponse();
    }

    /**
     * Create an instance of {@link ComplexObjectA }
     * 
     */
    public ComplexObjectA createComplexObjectA() {
        return new ComplexObjectA();
    }

    /**
     * Create an instance of {@link ComplexObjectB }
     * 
     */
    public ComplexObjectB createComplexObjectB() {
        return new ComplexObjectB();
    }

    /**
     * Create an instance of {@link FaultResponse }
     * 
     */
    public FaultResponse createFaultResponse() {
        return new FaultResponse();
    }

    /**
     * Create an instance of {@link FaultDetails }
     * 
     */
    public FaultDetails createFaultDetails() {
        return new FaultDetails();
    }

    /**
     * Create an instance of {@link RefData }
     * 
     */
    public RefData createRefData() {
        return new RefData();
    }

    /**
     * Create an instance of {@link Error }
     * 
     */
    public Error createError() {
        return new Error();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

}
