//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 10:38:42 AM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://integ.com/integration/test/rest/qoteandbuy/api")
package com.integ.integration.services.contracts.common.test.dto;
